CREATE TABLE SMS.TB_ROLE (
    ROLE_CD    VARCHAR2(30)  NOT NULL,
    ROLE_NM    VARCHAR2(100) NOT NULL,
    ROLE_DESC  VARCHAR2(500),
    SORT_ORD   NUMBER(5)     DEFAULT 0 NOT NULL,
    USE_YN     CHAR(1)       DEFAULT 'Y' NOT NULL,
    REG_ID     VARCHAR2(12)  NOT NULL,
    REG_DTTM   TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    UPD_ID     VARCHAR2(12),
    UPD_DTTM   TIMESTAMP(6),
    CONSTRAINT PK_TB_ROLE PRIMARY KEY (ROLE_CD),
    CONSTRAINT CK_TB_ROLE_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE TABLE SMS.TB_EMP_ROLE (
    EMP_ID    VARCHAR2(12) NOT NULL,
    DEP_ID    VARCHAR2(12) NOT NULL,
    ROLE_CD   VARCHAR2(30) NOT NULL,
    USE_YN    CHAR(1)      DEFAULT 'Y' NOT NULL,
    REG_ID    VARCHAR2(12) NOT NULL,
    REG_DTTM  TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPD_ID    VARCHAR2(12),
    UPD_DTTM  TIMESTAMP(6),
    CONSTRAINT PK_TB_EMP_ROLE PRIMARY KEY (EMP_ID, DEP_ID, ROLE_CD),
    CONSTRAINT FK_TB_EMP_ROLE_EMP FOREIGN KEY (EMP_ID, DEP_ID)
        REFERENCES SMS.EMP (EMP_ID, DEP_ID),
    CONSTRAINT FK_TB_EMP_ROLE_ROLE FOREIGN KEY (ROLE_CD)
        REFERENCES SMS.TB_ROLE (ROLE_CD),
    CONSTRAINT CK_TB_EMP_ROLE_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE INDEX SMS.IX_TB_EMP_ROLE_01 ON SMS.TB_EMP_ROLE (ROLE_CD);
CREATE INDEX SMS.IX_TB_EMP_ROLE_02 ON SMS.TB_EMP_ROLE (DEP_ID, EMP_ID);

CREATE TABLE SMS.TB_MENU (
    MENU_ID         VARCHAR2(50)  NOT NULL,
    PARENT_MENU_ID  VARCHAR2(50),
    MENU_NM         VARCHAR2(100) NOT NULL,
    MENU_URL        VARCHAR2(300),
    MENU_LEVEL      NUMBER(2)     NOT NULL,
    SORT_ORD        NUMBER(5)     DEFAULT 0 NOT NULL,
    MENU_TYPE       CHAR(1)       DEFAULT 'M' NOT NULL,
    ICON_NM         VARCHAR2(50),
    DISPLAY_YN      CHAR(1)       DEFAULT 'Y' NOT NULL,
    USE_YN          CHAR(1)       DEFAULT 'Y' NOT NULL,
    SYSTEM_YN       CHAR(1)       DEFAULT 'N' NOT NULL,
    REMARK          VARCHAR2(500),
    REG_ID          VARCHAR2(12)  NOT NULL,
    REG_DTTM        TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
    UPD_ID          VARCHAR2(12),
    UPD_DTTM        TIMESTAMP(6),
    CONSTRAINT PK_TB_MENU PRIMARY KEY (MENU_ID),
    CONSTRAINT FK_TB_MENU_PARENT FOREIGN KEY (PARENT_MENU_ID)
        REFERENCES SMS.TB_MENU (MENU_ID),
    CONSTRAINT CK_TB_MENU_TYPE CHECK (MENU_TYPE IN ('G', 'M')),
    CONSTRAINT CK_TB_MENU_DISPLAY_YN CHECK (DISPLAY_YN IN ('Y', 'N')),
    CONSTRAINT CK_TB_MENU_USE_YN CHECK (USE_YN IN ('Y', 'N')),
    CONSTRAINT CK_TB_MENU_SYSTEM_YN CHECK (SYSTEM_YN IN ('Y', 'N')),
    CONSTRAINT CK_TB_MENU_URL_BY_TYPE CHECK (
        (MENU_TYPE = 'G' AND MENU_URL IS NULL)
        OR (MENU_TYPE = 'M' AND MENU_URL IS NOT NULL)
    )
);

CREATE UNIQUE INDEX SMS.UX_TB_MENU_URL ON SMS.TB_MENU (MENU_URL);
CREATE INDEX SMS.IX_TB_MENU_01 ON SMS.TB_MENU (PARENT_MENU_ID, SORT_ORD);
CREATE INDEX SMS.IX_TB_MENU_02 ON SMS.TB_MENU (USE_YN, DISPLAY_YN);

CREATE TABLE SMS.TB_MENU_AUTH (
    MENU_ID        VARCHAR2(50) NOT NULL,
    ROLE_CD        VARCHAR2(30) NOT NULL,
    CAN_READ       CHAR(1)      DEFAULT 'N' NOT NULL,
    CAN_CREATE     CHAR(1)      DEFAULT 'N' NOT NULL,
    CAN_UPDATE     CHAR(1)      DEFAULT 'N' NOT NULL,
    CAN_DELETE     CHAR(1)      DEFAULT 'N' NOT NULL,
    CAN_APPROVE    CHAR(1)      DEFAULT 'N' NOT NULL,
    CAN_CANCEL     CHAR(1)      DEFAULT 'N' NOT NULL,
    CAN_DOWNLOAD   CHAR(1)      DEFAULT 'N' NOT NULL,
    CAN_MASK_VIEW  CHAR(1)      DEFAULT 'N' NOT NULL,
    USE_YN         CHAR(1)      DEFAULT 'Y' NOT NULL,
    REG_ID         VARCHAR2(12) NOT NULL,
    REG_DTTM       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPD_ID         VARCHAR2(12),
    UPD_DTTM       TIMESTAMP(6),
    CONSTRAINT PK_TB_MENU_AUTH PRIMARY KEY (MENU_ID, ROLE_CD),
    CONSTRAINT FK_TB_MENU_AUTH_MENU FOREIGN KEY (MENU_ID)
        REFERENCES SMS.TB_MENU (MENU_ID),
    CONSTRAINT FK_TB_MENU_AUTH_ROLE FOREIGN KEY (ROLE_CD)
        REFERENCES SMS.TB_ROLE (ROLE_CD),
    CONSTRAINT CK_TB_MENU_AUTH_READ CHECK (CAN_READ IN ('Y', 'N')),
    CONSTRAINT CK_TB_MENU_AUTH_CREATE CHECK (CAN_CREATE IN ('Y', 'N')),
    CONSTRAINT CK_TB_MENU_AUTH_UPDATE CHECK (CAN_UPDATE IN ('Y', 'N')),
    CONSTRAINT CK_TB_MENU_AUTH_DELETE CHECK (CAN_DELETE IN ('Y', 'N')),
    CONSTRAINT CK_TB_MENU_AUTH_APPROVE CHECK (CAN_APPROVE IN ('Y', 'N')),
    CONSTRAINT CK_TB_MENU_AUTH_CANCEL CHECK (CAN_CANCEL IN ('Y', 'N')),
    CONSTRAINT CK_TB_MENU_AUTH_DOWNLOAD CHECK (CAN_DOWNLOAD IN ('Y', 'N')),
    CONSTRAINT CK_TB_MENU_AUTH_MASK CHECK (CAN_MASK_VIEW IN ('Y', 'N')),
    CONSTRAINT CK_TB_MENU_AUTH_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE INDEX SMS.IX_TB_MENU_AUTH_01 ON SMS.TB_MENU_AUTH (ROLE_CD, USE_YN);