-- ============================================================
-- v3 개인정보 감사 로그 테이블 (DBA 검토 후 적용)
-- 정책: docs/base/audit-masking-policy.md
-- 주의: TARGET_DATA, ACTION_TYPE은 한글 저장 대상이므로 CHAR 단위 길이를 사용한다.
-- ============================================================

CREATE TABLE SMS.TB_PRIVACY_AUDIT_LOG (
    LOG_ID       NUMBER GENERATED ALWAYS AS IDENTITY,
    EMP_ID       VARCHAR2(12)        NOT NULL,
    DEP_ID       VARCHAR2(12)        NOT NULL,
    EXECUTOR_IP  VARCHAR2(45),
    REQUEST_URL  VARCHAR2(300)       NOT NULL,
    ACTION_TYPE  VARCHAR2(100 CHAR)  NOT NULL,
    TARGET_DATA  VARCHAR2(500 CHAR),
    REG_DTTM     TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_PRIVACY_AUDIT_LOG PRIMARY KEY (LOG_ID)
);

CREATE INDEX SMS.IX_TB_PRIVACY_AUDIT_01 ON SMS.TB_PRIVACY_AUDIT_LOG (EMP_ID, DEP_ID, REG_DTTM);
CREATE INDEX SMS.IX_TB_PRIVACY_AUDIT_02 ON SMS.TB_PRIVACY_AUDIT_LOG (REG_DTTM);

COMMENT ON TABLE SMS.TB_PRIVACY_AUDIT_LOG IS 'v3 개인정보 접근 감사 로그';
COMMENT ON COLUMN SMS.TB_PRIVACY_AUDIT_LOG.EMP_ID IS '행위자 직원 ID. EMP.EMP_ID';
COMMENT ON COLUMN SMS.TB_PRIVACY_AUDIT_LOG.DEP_ID IS '행위자 부서 ID. EMP.DEP_ID';
COMMENT ON COLUMN SMS.TB_PRIVACY_AUDIT_LOG.EXECUTOR_IP IS '요청 IP';
COMMENT ON COLUMN SMS.TB_PRIVACY_AUDIT_LOG.REQUEST_URL IS '요청 URL';
COMMENT ON COLUMN SMS.TB_PRIVACY_AUDIT_LOG.ACTION_TYPE IS '수행 업무명 (@PrivacyLog action)';
COMMENT ON COLUMN SMS.TB_PRIVACY_AUDIT_LOG.TARGET_DATA IS '마스킹된 요청 파라미터 (개인정보 원문 저장 금지)';
