-- ============================================================
-- SMS 발송 이력 테이블 (DBA 검토 후 적용)
-- 기준: v3 업무 테이블은 TB_ 접두어가 아닌 실제 운영명 SMS_HISTORY를 사용한다.
-- 주의: MESSAGE, RESULT_MSG는 한글 저장 대상이므로 CHAR 단위 길이 또는 CLOB을 사용한다.
-- ============================================================

CREATE TABLE SMS.SMS_HISTORY (
    SMS_HISTORY_ID  NUMBER GENERATED ALWAYS AS IDENTITY,
    REQUEST_ID      VARCHAR2(50)       NOT NULL,
    SENT_AT         TIMESTAMP(6)       NOT NULL,
    RECEIVER_NO     VARCHAR2(20)       NOT NULL,
    SENDER_NO       VARCHAR2(20),
    SEND_TYPE       VARCHAR2(20)       NOT NULL,
    SEND_STATUS     VARCHAR2(20)       DEFAULT 'SENT' NOT NULL,
    RESULT_CD       VARCHAR2(30),
    RESULT_MSG      VARCHAR2(500 CHAR),
    MESSAGE         CLOB,
    EMP_ID          VARCHAR2(12),
    DEP_ID          VARCHAR2(12),
    REG_ID          VARCHAR2(12)       NOT NULL,
    REG_DTTM        TIMESTAMP(6)       DEFAULT SYSTIMESTAMP NOT NULL,
    UPD_ID          VARCHAR2(12),
    UPD_DTTM        TIMESTAMP(6),
    CONSTRAINT PK_SMS_HISTORY PRIMARY KEY (SMS_HISTORY_ID),
    CONSTRAINT UX_SMS_HISTORY_REQUEST UNIQUE (REQUEST_ID),
    CONSTRAINT FK_SMS_HISTORY_EMP FOREIGN KEY (EMP_ID, DEP_ID)
        REFERENCES SMS.EMP (EMP_ID, DEP_ID),
    CONSTRAINT CK_SMS_HISTORY_SEND_TYPE CHECK (SEND_TYPE IN ('SMS', 'LMS', 'MMS', 'ALIMTALK')),
    CONSTRAINT CK_SMS_HISTORY_STATUS CHECK (SEND_STATUS IN ('READY', 'SENT', 'SUCCESS', 'FAIL', 'CANCEL'))
);

CREATE INDEX SMS.IX_SMS_HISTORY_01 ON SMS.SMS_HISTORY (SENT_AT DESC);
CREATE INDEX SMS.IX_SMS_HISTORY_02 ON SMS.SMS_HISTORY (RECEIVER_NO, SENT_AT DESC);
CREATE INDEX SMS.IX_SMS_HISTORY_03 ON SMS.SMS_HISTORY (EMP_ID, DEP_ID, SENT_AT DESC);
CREATE INDEX SMS.IX_SMS_HISTORY_04 ON SMS.SMS_HISTORY (SEND_TYPE, SEND_STATUS, SENT_AT DESC);

COMMENT ON TABLE SMS.SMS_HISTORY IS 'SMS/LMS/MMS/알림톡 발송 이력';
COMMENT ON COLUMN SMS.SMS_HISTORY.SMS_HISTORY_ID IS '발송 이력 PK';
COMMENT ON COLUMN SMS.SMS_HISTORY.REQUEST_ID IS '발송 요청 식별자. 재실행 seed 및 외부 연계 추적 기준';
COMMENT ON COLUMN SMS.SMS_HISTORY.SENT_AT IS '발송 일시';
COMMENT ON COLUMN SMS.SMS_HISTORY.RECEIVER_NO IS '수신자 전화번호. 개인정보';
COMMENT ON COLUMN SMS.SMS_HISTORY.SENDER_NO IS '발신 번호';
COMMENT ON COLUMN SMS.SMS_HISTORY.SEND_TYPE IS '발송 유형: SMS, LMS, MMS, ALIMTALK';
COMMENT ON COLUMN SMS.SMS_HISTORY.SEND_STATUS IS '발송 상태: READY, SENT, SUCCESS, FAIL, CANCEL';
COMMENT ON COLUMN SMS.SMS_HISTORY.RESULT_CD IS '발송 결과 코드';
COMMENT ON COLUMN SMS.SMS_HISTORY.RESULT_MSG IS '발송 결과 메시지';
COMMENT ON COLUMN SMS.SMS_HISTORY.MESSAGE IS '발송 메시지 본문';
COMMENT ON COLUMN SMS.SMS_HISTORY.EMP_ID IS '발송 사용자 EMP.EMP_ID';
COMMENT ON COLUMN SMS.SMS_HISTORY.DEP_ID IS '발송 사용자 EMP.DEP_ID';
COMMENT ON COLUMN SMS.SMS_HISTORY.REG_ID IS '등록자';
COMMENT ON COLUMN SMS.SMS_HISTORY.REG_DTTM IS '등록 일시';
COMMENT ON COLUMN SMS.SMS_HISTORY.UPD_ID IS '수정자';
COMMENT ON COLUMN SMS.SMS_HISTORY.UPD_DTTM IS '수정 일시';
