-- ============================================================
-- 공지사항 테이블 (scaffold 테스트용)
-- 기준: v3 업무 테이블은 TB_ 접두어가 아닌 실제 운영명 NOTICE를 사용한다.
-- 주의: TITLE, CONTENT는 한글 저장 대상이므로 CHAR 단위 길이 또는 CLOB을 사용한다.
-- ============================================================

CREATE TABLE SMS.NOTICE (
    NOTICE_ID     NUMBER GENERATED ALWAYS AS IDENTITY,
    TITLE         VARCHAR2(200 CHAR)  NOT NULL,
    CONTENT       CLOB                NOT NULL,
    NOTICE_TYPE   VARCHAR2(20)        DEFAULT 'GENERAL' NOT NULL,
    USE_YN        VARCHAR2(1)         DEFAULT 'Y' NOT NULL,
    START_DT      DATE,
    END_DT        DATE,
    VIEW_CNT      NUMBER              DEFAULT 0 NOT NULL,
    REG_ID        VARCHAR2(12)        NOT NULL,
    REG_DTTM      TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
    UPD_ID        VARCHAR2(12),
    UPD_DTTM      TIMESTAMP(6),
    CONSTRAINT PK_NOTICE PRIMARY KEY (NOTICE_ID),
    CONSTRAINT CK_NOTICE_TYPE CHECK (NOTICE_TYPE IN ('GENERAL', 'URGENT', 'EVENT')),
    CONSTRAINT CK_NOTICE_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE INDEX SMS.IX_NOTICE_01 ON SMS.NOTICE (USE_YN, START_DT DESC);
CREATE INDEX SMS.IX_NOTICE_02 ON SMS.NOTICE (REG_DTTM DESC);

COMMENT ON TABLE SMS.NOTICE IS '공지사항';
COMMENT ON COLUMN SMS.NOTICE.NOTICE_ID IS '공지사항 PK';
COMMENT ON COLUMN SMS.NOTICE.TITLE IS '제목';
COMMENT ON COLUMN SMS.NOTICE.CONTENT IS '내용';
COMMENT ON COLUMN SMS.NOTICE.NOTICE_TYPE IS '공지 유형: GENERAL, URGENT, EVENT';
COMMENT ON COLUMN SMS.NOTICE.USE_YN IS '게시 여부: Y, N';
COMMENT ON COLUMN SMS.NOTICE.START_DT IS '게시 시작일';
COMMENT ON COLUMN SMS.NOTICE.END_DT IS '게시 종료일';
COMMENT ON COLUMN SMS.NOTICE.VIEW_CNT IS '조회수';
COMMENT ON COLUMN SMS.NOTICE.REG_ID IS '등록자';
COMMENT ON COLUMN SMS.NOTICE.REG_DTTM IS '등록 일시';
COMMENT ON COLUMN SMS.NOTICE.UPD_ID IS '수정자';
COMMENT ON COLUMN SMS.NOTICE.UPD_DTTM IS '수정 일시';
